<?php

/**
 * @file
 * Provides SSO OpenID Connect login validation for WissKI groups.
 */

/**
 * Implements hook_openid_connect_authorize_alter().
 */
function soda_wisski_user_administration_openid_connect_authorize_alter(array &$user_data, array $context) {
  // Check if group information is provided in the user data.
  if (isset($user_data['groups'])) {
    $validGroups = ['wisski_admin'];

    // Add current site domain as valid group if it matches the pattern.
    $currentDomain = \Drupal::request()->getHost();
    if (preg_match('/wisski-([\w-]+)\.wisski\.scs\.sammlungen\.io/', $currentDomain, $matches)) {
      $validGroups[] = $matches[0];
    }

    // Filter user groups to only include valid ones.
    $user_data['groups'] = array_intersect($user_data['groups'], $validGroups);
  }
}
